"""finance: accounts, categories, transactions, budgets, goals, recurring

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-05 03:19:14.283369
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "opening_balance", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "current_balance", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False
        ),
        sa.Column("credit_limit", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("is_liquid", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("institution", sa.String(length=120), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "type <> 'credit_card' OR credit_limit IS NOT NULL",
            name=op.f("ck_accounts_credit_limit_required"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_index(
        "ix_accounts_user_id_active",
        "accounts",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_accounts_user_id_name",
        "accounts",
        ["user_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "categories",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_categories_no_self_parent")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False)
    op.create_index(
        "uq_categories_scope_slug",
        "categories",
        [
            sa.literal_column("COALESCE(user_id, '00000000-0000-0000-0000-000000000000'::uuid)"),
            "slug",
        ],
        unique=True,
    )
    op.create_table(
        "budgets",
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("period", sa.String(length=20), server_default="monthly", nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("amount_limit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "rollover_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "rollover_amount", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount_limit > 0", name=op.f("ck_budgets_limit_positive")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_budgets_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
    )
    op.create_index(op.f("ix_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.create_index(
        "ix_budgets_user_id_period_start",
        "budgets",
        ["user_id", sa.literal_column("period_start DESC")],
        unique=False,
    )
    op.create_index(
        "uq_budgets_user_id_category_id_period_start",
        "budgets",
        [
            "user_id",
            sa.literal_column(
                "COALESCE(category_id, '00000000-0000-0000-0000-000000000000'::uuid)"
            ),
            "period_start",
        ],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "goals",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "current_amount", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("linked_account_id", sa.UUID(), nullable=True),
        sa.Column("priority", sa.SmallInteger(), server_default="3", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name=op.f("ck_goals_priority_range")),
        sa.CheckConstraint("target_amount > 0", name=op.f("ck_goals_target_positive")),
        sa.ForeignKeyConstraint(
            ["linked_account_id"],
            ["accounts.id"],
            name=op.f("fk_goals_linked_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_index(
        "ix_goals_user_id_status",
        "goals",
        ["user_id", "status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "recurring_items",
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("cadence", sa.String(length=20), nullable=False),
        sa.Column("next_due_on", sa.Date(), nullable=False),
        sa.Column("end_on", sa.Date(), nullable=True),
        sa.Column("amount_variance", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("detection_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "is_auto_detected", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_recurring_items_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_recurring_items_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_recurring_items_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_items")),
    )
    op.create_index(
        op.f("ix_recurring_items_user_id"), "recurring_items", ["user_id"], unique=False
    )
    op.create_index(
        "ix_recurring_items_user_id_item_type",
        "recurring_items",
        ["user_id", "item_type"],
        unique=False,
    )
    op.create_index(
        "ix_recurring_items_user_id_next_due_on",
        "recurring_items",
        ["user_id", "next_due_on"],
        unique=False,
        postgresql_where=sa.text("is_active AND deleted_at IS NULL"),
    )
    op.create_table(
        "transactions",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("merchant_raw", sa.String(length=255), nullable=True),
        sa.Column("merchant_normalized", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transfer_pair_id", sa.UUID(), nullable=True),
        sa.Column("recurring_item_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("category_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("categorizer_version", sa.String(length=32), nullable=True),
        sa.Column("is_reviewed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "excluded_from_analytics", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transactions_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_transactions_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recurring_item_id"],
            ["recurring_items.id"],
            name=op.f("fk_transactions_recurring_item_id_recurring_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_pair_id"],
            ["transactions.id"],
            name=op.f("fk_transactions_transfer_pair_id_transactions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(
        "ix_transactions_merchant_trgm",
        "transactions",
        ["merchant_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"merchant_normalized": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_transactions_uncategorized",
        "transactions",
        ["user_id", sa.literal_column("occurred_on DESC")],
        unique=False,
        postgresql_where=sa.text("category_id IS NULL AND deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_index(
        "ix_transactions_user_id_account_id_occurred_on",
        "transactions",
        ["user_id", "account_id", sa.literal_column("occurred_on DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_transactions_user_id_category_id_occurred_on",
        "transactions",
        ["user_id", "category_id", sa.literal_column("occurred_on DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_transactions_user_id_occurred_on",
        "transactions",
        ["user_id", sa.literal_column("occurred_on DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_transactions_user_id_content_hash",
        "transactions",
        ["user_id", "content_hash"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_transactions_user_id_content_hash",
        table_name="transactions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_transactions_user_id_occurred_on",
        table_name="transactions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_transactions_user_id_category_id_occurred_on",
        table_name="transactions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_transactions_user_id_account_id_occurred_on",
        table_name="transactions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(
        "ix_transactions_uncategorized",
        table_name="transactions",
        postgresql_where=sa.text("category_id IS NULL AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_transactions_merchant_trgm",
        table_name="transactions",
        postgresql_using="gin",
        postgresql_ops={"merchant_normalized": "gin_trgm_ops"},
    )
    op.drop_table("transactions")
    op.drop_index(
        "ix_recurring_items_user_id_next_due_on",
        table_name="recurring_items",
        postgresql_where=sa.text("is_active AND deleted_at IS NULL"),
    )
    op.drop_index("ix_recurring_items_user_id_item_type", table_name="recurring_items")
    op.drop_index(op.f("ix_recurring_items_user_id"), table_name="recurring_items")
    op.drop_table("recurring_items")
    op.drop_index(
        "ix_goals_user_id_status",
        table_name="goals",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(
        "uq_budgets_user_id_category_id_period_start",
        table_name="budgets",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_budgets_user_id_period_start", table_name="budgets")
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index("uq_categories_scope_slug", table_name="categories")
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(
        "uq_accounts_user_id_name",
        table_name="accounts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_accounts_user_id_active",
        table_name="accounts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
