"""receipts: jobs, receipts, fields, line items

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-05 04:57:15.739821
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("task_name", sa.String(length=120), nullable=False),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("error_type", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("celery_task_id", name=op.f("uq_jobs_celery_task_id")),
    )
    op.create_index("ix_jobs_status_created_at", "jobs", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
    op.create_index("ix_jobs_user_id_created_at", "jobs", ["user_id", "created_at"], unique=False)
    op.create_index(
        "uq_jobs_idempotency_key", "jobs", ["idempotency_key"], unique=True, postgresql_where=None
    )
    op.create_table(
        "receipts",
        sa.Column("s3_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending_upload", nullable=False),
        sa.Column("merchant_extracted", sa.String(length=255), nullable=True),
        sa.Column("total_extracted", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("date_extracted", sa.Date(), nullable=True),
        sa.Column("tax_extracted", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("overall_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("ocr_engine_version", sa.String(length=32), nullable=True),
        sa.Column("preprocess_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("committed_transaction_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "file_size_bytes > 0 AND file_size_bytes <= 10485760",
            name=op.f("ck_receipts_file_size_within_limit"),
        ),
        sa.ForeignKeyConstraint(
            ["committed_transaction_id"],
            ["transactions.id"],
            name=op.f("fk_receipts_committed_transaction_id_transactions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
    )
    op.create_index(op.f("ix_receipts_user_id"), "receipts", ["user_id"], unique=False)
    op.create_index(
        "ix_receipts_user_id_created_at",
        "receipts",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_receipts_user_id_status",
        "receipts",
        ["user_id", "status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "receipt_fields",
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=20), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("parsed_value", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("corrected_value", sa.Text(), nullable=True),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_fields_receipt_id_receipts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_fields")),
    )
    op.create_index(
        "ix_receipt_fields_review_queue",
        "receipt_fields",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("needs_review AND corrected_at IS NULL"),
    )
    op.create_index(op.f("ix_receipt_fields_user_id"), "receipt_fields", ["user_id"], unique=False)
    op.create_index(
        "uq_receipt_fields_receipt_id_field_name",
        "receipt_fields",
        ["receipt_id", "field_name"],
        unique=True,
    )
    op.create_table(
        "receipt_line_items",
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("line_number", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_line_items_receipt_id_receipts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_line_items")),
    )
    op.create_index(
        op.f("ix_receipt_line_items_user_id"), "receipt_line_items", ["user_id"], unique=False
    )
    op.create_index(
        "uq_receipt_line_items_receipt_id_line_number",
        "receipt_line_items",
        ["receipt_id", "line_number"],
        unique=True,
    )
    op.add_column("transactions", sa.Column("receipt_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_transactions_receipt_id_receipts"),
        "transactions",
        "receipts",
        ["receipt_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transactions_receipt_id_receipts"), "transactions", type_="foreignkey"
    )
    op.drop_column("transactions", "receipt_id")
    op.drop_index("uq_receipt_line_items_receipt_id_line_number", table_name="receipt_line_items")
    op.drop_index(op.f("ix_receipt_line_items_user_id"), table_name="receipt_line_items")
    op.drop_table("receipt_line_items")
    op.drop_index("uq_receipt_fields_receipt_id_field_name", table_name="receipt_fields")
    op.drop_index(op.f("ix_receipt_fields_user_id"), table_name="receipt_fields")
    op.drop_index(
        "ix_receipt_fields_review_queue",
        table_name="receipt_fields",
        postgresql_where=sa.text("needs_review AND corrected_at IS NULL"),
    )
    op.drop_table("receipt_fields")
    op.drop_index(
        "ix_receipts_user_id_status",
        table_name="receipts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_receipts_user_id_created_at", table_name="receipts")
    op.drop_index(op.f("ix_receipts_user_id"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index("uq_jobs_idempotency_key", table_name="jobs", postgresql_where=None)
    op.drop_index("ix_jobs_user_id_created_at", table_name="jobs")
    op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
    op.drop_index("ix_jobs_status_created_at", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
