"""categorization feedback

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-05 08:35:22.468793
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorization_feedback",
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("merchant_normalized", sa.String(length=255), nullable=False),
        sa.Column("predicted_category_id", sa.UUID(), nullable=True),
        sa.Column("corrected_category_id", sa.UUID(), nullable=False),
        sa.Column("predicted_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("categorizer_version", sa.String(length=48), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["corrected_category_id"],
            ["categories.id"],
            name=op.f("fk_categorization_feedback_corrected_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["predicted_category_id"],
            ["categories.id"],
            name=op.f("fk_categorization_feedback_predicted_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_categorization_feedback_transaction_id_transactions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categorization_feedback")),
    )
    op.create_index(
        "ix_categorization_feedback_created_at",
        "categorization_feedback",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_categorization_feedback_user_id"),
        "categorization_feedback",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_categorization_feedback_user_id_merchant",
        "categorization_feedback",
        ["user_id", "merchant_normalized", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_categorization_feedback_user_id_merchant", table_name="categorization_feedback"
    )
    op.drop_index(op.f("ix_categorization_feedback_user_id"), table_name="categorization_feedback")
    op.drop_index("ix_categorization_feedback_created_at", table_name="categorization_feedback")
    op.drop_table("categorization_feedback")
    # ### end Alembic commands ###
