"""health snapshots

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-05 12:52:34.086420
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_snapshots",
        sa.Column("snapshot_on", sa.Date(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("rubric_version", sa.String(length=16), nullable=False),
        sa.Column("savings_rate_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("emergency_fund_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("debt_to_income_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("budget_discipline_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("cashflow_stability_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("growth_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "overall_score >= 0 AND overall_score <= 100",
            name=op.f("ck_health_snapshots_ck_health_score_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_snapshots")),
        sa.UniqueConstraint("user_id", "snapshot_on", name="uq_health_snapshots"),
    )
    op.create_index(
        "ix_health_snapshots_user_date",
        "health_snapshots",
        ["user_id", sa.literal_column("snapshot_on DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_snapshots_user_id"), "health_snapshots", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_health_snapshots_user_id"), table_name="health_snapshots")
    op.drop_index("ix_health_snapshots_user_date", table_name="health_snapshots")
    op.drop_table("health_snapshots")
    # ### end Alembic commands ###
