"""insights

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-05 13:41:40.496269
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insights",
        sa.Column("insight_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("impact_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("materiality", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["transactions.id"],
            name=op.f("fk_insights_subject_id_transactions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insights")),
        sa.UniqueConstraint("user_id", "dedup_key", "period_start", name="uq_insights_dedup"),
    )
    op.create_index(
        "ix_insights_user_active",
        "insights",
        ["user_id", "materiality"],
        unique=False,
        postgresql_where="dismissed_at IS NULL AND deleted_at IS NULL",
    )
    op.create_index("ix_insights_user_created", "insights", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_insights_user_id"), "insights", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_insights_user_id"), table_name="insights")
    op.drop_index("ix_insights_user_created", table_name="insights")
    op.drop_index(
        "ix_insights_user_active",
        table_name="insights",
        postgresql_where="dismissed_at IS NULL AND deleted_at IS NULL",
    )
    op.drop_table("insights")
    # ### end Alembic commands ###
