"""forecasts

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-05 14:11:37.473980
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecasts",
        sa.Column("generated_on", sa.Date(), nullable=False),
        sa.Column("horizon_days", sa.SmallInteger(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("observation_days", sa.SmallInteger(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("projected_balance_end", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("trough_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("trough_on", sa.Date(), nullable=False),
        sa.Column(
            "shortfall_dates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("series", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_version", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecasts")),
    )
    op.create_index(
        "ix_forecasts_user_gen",
        "forecasts",
        ["user_id", sa.literal_column("generated_on DESC"), "horizon_days"],
        unique=False,
    )
    op.create_index(op.f("ix_forecasts_user_id"), "forecasts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_forecasts_user_id"), table_name="forecasts")
    op.drop_index("ix_forecasts_user_gen", table_name="forecasts")
    op.drop_table("forecasts")
    # ### end Alembic commands ###
