"""advisor catalogue and evaluations

Revision ID: 0011
Revises: 0010
Create Date: 2026-08-05 15:13:05.684030
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column(
            "specs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("external_id", name="uq_products_external_id"),
    )
    op.create_index("ix_products_category", "products", ["category"], unique=False)
    op.create_index("ix_products_name", "products", ["canonical_name"], unique=False)
    op.create_table(
        "price_points",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("seller_name", sa.String(length=120), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("in_stock", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("seller_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("rating_count", sa.Integer(), nullable=True),
        sa.Column("return_window_days", sa.SmallInteger(), nullable=True),
        sa.Column("warranty_months", sa.SmallInteger(), nullable=True),
        sa.Column("fulfillment_type", sa.String(length=20), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_price_points_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_points")),
        sa.UniqueConstraint(
            "product_id", "seller_name", "observed_at", name="uq_price_points_snapshot"
        ),
    )
    op.create_index(
        "ix_price_points_product_time",
        "price_points",
        ["product_id", sa.literal_column("observed_at DESC")],
        unique=False,
    )
    op.create_table(
        "purchase_evaluations",
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("product_query", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("affordability_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("rubric_version", sa.String(length=16), nullable=False),
        sa.Column("affordable_from", sa.Date(), nullable=True),
        sa.Column("goal_delay_days", sa.Integer(), nullable=True),
        sa.Column("emergency_fund_delta_months", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("health_score_delta", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("simulation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("emi_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("alternatives", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict <> 'wait' OR affordable_from IS NOT NULL",
            name=op.f("ck_purchase_evaluations_ck_purchase_eval_wait_date"),
        ),
        sa.CheckConstraint(
            "affordability_score >= 0 AND affordability_score <= 100",
            name=op.f("ck_purchase_evaluations_ck_purchase_eval_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchase_evaluations_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_evaluations")),
    )
    op.create_index(
        "ix_purchase_eval_user_created",
        "purchase_evaluations",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_evaluations_user_id"), "purchase_evaluations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_evaluations_user_id"), table_name="purchase_evaluations")
    op.drop_index("ix_purchase_eval_user_created", table_name="purchase_evaluations")
    op.drop_table("purchase_evaluations")
    op.drop_index("ix_price_points_product_time", table_name="price_points")
    op.drop_table("price_points")
    op.drop_index("ix_products_name", table_name="products")
    op.drop_index("ix_products_category", table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
