"""wishlist partial unique

Revision ID: 0013
Revises: 0012
Create Date: 2026-08-06 01:05:52.997593
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_wishlist_user_product"), "wishlist_items", type_="unique")
    op.create_index(
        "uq_wishlist_user_product",
        "wishlist_items",
        ["user_id", "product_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_wishlist_user_product",
        table_name="wishlist_items",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_wishlist_user_product"),
        "wishlist_items",
        ["user_id", "product_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
