"""Erasure requests: the outbox that carries deletion across a database boundary.

A cascading foreign key cannot reach the personalization database (ADR-011),
and no transaction spans the two. So the debt is recorded here, in the same
transaction as the account deletion, and drained by an idempotent sweep --
`app/workers/tasks/personalization.py::run_erasure`, hourly.

No foreign key to `users`, for the same reason `audit_log` has none: the row
exists precisely because the user does not.

Revision ID: 0020
Revises: 0019
Create Date: 2026-08-25 22:37:35.474200
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "erasure_requests",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_erasure_requests")),
        sa.UniqueConstraint("subject_id", "kind", name="uq_erasure_requests_subject_id_kind"),
    )
    op.create_index(
        "ix_erasure_requests_pending",
        "erasure_requests",
        ["requested_at"],
        unique=False,
        postgresql_where=sa.text("completed_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_erasure_requests_pending",
        table_name="erasure_requests",
        postgresql_where=sa.text("completed_at IS NULL"),
    )
    op.drop_table("erasure_requests")
    # ### end Alembic commands ###
