"""The crowdsourced price graph, and the points ledger (ADR-013).

Two kinds of table, and which is which is the whole privacy design.

GLOBAL, carrying no `user_id`: `stores`, `canonical_items`,
`canonical_item_aliases`, `item_merge_candidates`, `price_observations`,
`receipt_fingerprints`, `rewards`. A price at a shop on a day is a fact about
the shop, by the same reasoning that keeps `products` and `offer_snapshots`
ownerless.

TENANT-SCOPED, cascading from `users`: `user_store_pins`, `receipt_promotions`,
`points_ledger`. `receipt_promotions` is the join `price_observations`
deliberately does not carry -- deleting an account destroys the ability to
attribute an observation to anybody, while the observation survives as the
shared fact it always was.

Note what `price_observations` does not have and cannot be given: no
`receipt_id`, no line number, no timestamp. Item co-occurrence on one receipt is
a fingerprint that re-identifies people with no name attached, so the shared row
records one item and not the shopping trip it came from.

Revision ID: 0021
Revises: 0020
Create Date: 2026-08-26 10:53:02.715261
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_items",
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("normalized_key", sa.String(length=200), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=True),
        sa.Column("pack_size", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("pack_unit", sa.String(length=8), nullable=True),
        sa.Column("category_slug", sa.String(length=80), nullable=True),
        sa.Column("is_provisional", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("observation_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("normalizer_version", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_items")),
        sa.UniqueConstraint("normalized_key", name="uq_canonical_items_normalized_key"),
    )
    op.create_index(
        "ix_canonical_items_brand_pack_size_pack_unit",
        "canonical_items",
        ["brand", "pack_size", "pack_unit"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_items_category_slug"), "canonical_items", ["category_slug"], unique=False
    )
    op.create_index(
        "ix_canonical_items_normalized_key_trgm",
        "canonical_items",
        ["normalized_key"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_key": "gin_trgm_ops"},
    )
    op.create_table(
        "receipt_fingerprints",
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("phash", sa.BigInteger(), nullable=False),
        sa.Column("observed_on", sa.Date(), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("first_seen_on", sa.Date(), nullable=False),
        sa.Column("sighting_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_fingerprints")),
        sa.UniqueConstraint("content_hash", name="uq_receipt_fingerprints_content_hash"),
    )
    op.create_index(
        "ix_receipt_fingerprints_observed_on_total",
        "receipt_fingerprints",
        ["observed_on", "total"],
        unique=False,
    )
    op.create_index(
        "ix_receipt_fingerprints_phash_observed_on",
        "receipt_fingerprints",
        ["phash", "observed_on"],
        unique=False,
    )
    op.create_table(
        "rewards",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=False),
        sa.Column("cost_points", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cost_points > 0", name=op.f("ck_rewards_a_reward_costs_something")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rewards")),
        sa.UniqueConstraint("slug", name=op.f("uq_rewards_slug")),
    )
    op.create_table(
        "stores",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column("brand_slug", sa.String(length=80), nullable=True),
        sa.Column("address_line", sa.String(length=255), nullable=True),
        sa.Column("pincode", sa.String(length=6), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=80), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("osm_id", sa.String(length=40), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(latitude IS NULL) = (longitude IS NULL)",
            name=op.f("ck_stores_coordinates_come_in_pairs"),
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)",
            name=op.f("ck_stores_coordinates_are_on_earth"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
        sa.UniqueConstraint("gstin", name="uq_stores_gstin"),
        sa.UniqueConstraint("osm_id", name="uq_stores_osm_id"),
    )
    op.create_index(op.f("ix_stores_brand_slug"), "stores", ["brand_slug"], unique=False)
    op.create_index(
        "ix_stores_latitude_longitude", "stores", ["latitude", "longitude"], unique=False
    )
    op.create_index(
        "ix_stores_normalized_name_trgm",
        "stores",
        ["normalized_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_stores_pincode_normalized_name", "stores", ["pincode", "normalized_name"], unique=False
    )
    op.create_table(
        "canonical_item_aliases",
        sa.Column("canonical_item_id", sa.UUID(), nullable=False),
        sa.Column("alias_key", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("confirmed_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_item_id"],
            ["canonical_items.id"],
            name=op.f("fk_canonical_item_aliases_canonical_item_id_canonical_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_item_aliases")),
        sa.UniqueConstraint("alias_key", name="uq_canonical_item_aliases_alias_key"),
    )
    op.create_index(
        op.f("ix_canonical_item_aliases_canonical_item_id"),
        "canonical_item_aliases",
        ["canonical_item_id"],
        unique=False,
    )
    op.create_table(
        "item_merge_candidates",
        sa.Column("left_item_id", sa.UUID(), nullable=False),
        sa.Column("right_item_id", sa.UUID(), nullable=False),
        sa.Column("similarity", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "left_item_id < right_item_id",
            name=op.f("ck_item_merge_candidates_one_row_per_unordered_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["left_item_id"],
            ["canonical_items.id"],
            name=op.f("fk_item_merge_candidates_left_item_id_canonical_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["right_item_id"],
            ["canonical_items.id"],
            name=op.f("fk_item_merge_candidates_right_item_id_canonical_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_merge_candidates")),
        sa.UniqueConstraint("left_item_id", "right_item_id", name="uq_item_merge_candidates_pair"),
    )
    op.create_index(
        op.f("ix_item_merge_candidates_left_item_id"),
        "item_merge_candidates",
        ["left_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_merge_candidates_right_item_id"),
        "item_merge_candidates",
        ["right_item_id"],
        unique=False,
    )
    op.create_table(
        "points_ledger",
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("subject_type", sa.String(length=40), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("reverses_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "points <> 0", name=op.f("ck_points_ledger_an_award_of_nothing_is_not_an_award")
        ),
        sa.ForeignKeyConstraint(
            ["reverses_id"],
            ["points_ledger.id"],
            name=op.f("fk_points_ledger_reverses_id_points_ledger"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_points_ledger_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_points_ledger")),
        sa.UniqueConstraint("idempotency_key", name="uq_points_ledger_idempotency_key"),
    )
    op.create_index(
        op.f("ix_points_ledger_reverses_id"), "points_ledger", ["reverses_id"], unique=False
    )
    op.create_index(
        op.f("ix_points_ledger_subject_id"), "points_ledger", ["subject_id"], unique=False
    )
    op.create_index(op.f("ix_points_ledger_user_id"), "points_ledger", ["user_id"], unique=False)
    op.create_index(
        "ix_points_ledger_user_id_created_at",
        "points_ledger",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "price_observations",
        sa.Column("canonical_item_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("pack_size", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("pack_unit", sa.String(length=8), nullable=True),
        sa.Column("observed_on", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("contributor_hash", sa.LargeBinary(length=16), nullable=True),
        sa.Column("pepper_version", sa.SmallInteger(), nullable=True),
        sa.Column("retracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "unit_price > 0", name=op.f("ck_price_observations_unit_price_positive")
        ),
        sa.ForeignKeyConstraint(
            ["canonical_item_id"],
            ["canonical_items.id"],
            name=op.f("fk_price_observations_canonical_item_id_canonical_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_price_observations_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_observations")),
        sa.UniqueConstraint(
            "canonical_item_id",
            "store_id",
            "observed_on",
            "contributor_hash",
            name="uq_price_observations_one_per_contributor_per_day",
        ),
    )
    op.create_index(
        op.f("ix_price_observations_canonical_item_id"),
        "price_observations",
        ["canonical_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_price_observations_item_store_date",
        "price_observations",
        ["canonical_item_id", "store_id", sa.literal_column("observed_on DESC")],
        unique=False,
        postgresql_where=sa.text("retracted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_price_observations_store_id"), "price_observations", ["store_id"], unique=False
    )
    op.create_index(
        "ix_price_observations_store_id_observed_on",
        "price_observations",
        ["store_id", sa.literal_column("observed_on DESC")],
        unique=False,
    )
    op.create_table(
        "user_store_pins",
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("pincode", sa.String(length=6), nullable=True),
        sa.Column("note", sa.String(length=400), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180",
            name=op.f("ck_user_store_pins_pin_is_on_earth"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_user_store_pins_store_id_stores"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_store_pins_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_store_pins")),
    )
    op.create_index(
        op.f("ix_user_store_pins_store_id"), "user_store_pins", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_store_pins_user_id"), "user_store_pins", ["user_id"], unique=False
    )
    op.create_table(
        "receipt_promotions",
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("receipt_line_item_id", sa.UUID(), nullable=False),
        sa.Column("price_observation_id", sa.UUID(), nullable=True),
        sa.Column("points_awarded", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["price_observation_id"],
            ["price_observations.id"],
            name=op.f("fk_receipt_promotions_price_observation_id_price_observations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_promotions_receipt_id_receipts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_line_item_id"],
            ["receipt_line_items.id"],
            name=op.f("fk_receipt_promotions_receipt_line_item_id_receipt_line_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_receipt_promotions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_promotions")),
        sa.UniqueConstraint(
            "receipt_line_item_id", name="uq_receipt_promotions_receipt_line_item_id"
        ),
    )
    op.create_index(
        op.f("ix_receipt_promotions_price_observation_id"),
        "receipt_promotions",
        ["price_observation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_receipt_promotions_receipt_id"), "receipt_promotions", ["receipt_id"], unique=False
    )
    op.create_index(
        op.f("ix_receipt_promotions_receipt_line_item_id"),
        "receipt_promotions",
        ["receipt_line_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_receipt_promotions_user_id"), "receipt_promotions", ["user_id"], unique=False
    )
    op.add_column("receipts", sa.Column("fingerprint_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_receipts_fingerprint_id"), "receipts", ["fingerprint_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_receipts_fingerprint_id_receipt_fingerprints"),
        "receipts",
        "receipt_fingerprints",
        ["fingerprint_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    _seed_rewards()


def _seed_rewards() -> None:
    """Seed the rewards catalogue, as migration 0004 seeds the category taxonomy.

    Reference data belongs in a migration rather than in a startup hook: a
    startup sync is idempotent and non-fatal, which means a process booted
    against a schema that lacks the table serves an empty catalogue for its
    whole life and nothing retries. That exact failure cost the M9 market specs
    an afternoon.

    Deterministic UUIDs from the slug, so a re-run is a no-op and a reward's id
    is stable across environments.
    """
    import uuid

    from sqlalchemy import table, column, String, Integer, Boolean
    from sqlalchemy.dialects.postgresql import UUID as PgUUID

    rewards = table(
        "rewards",
        column("id", PgUUID(as_uuid=True)),
        column("slug", String),
        column("title", String),
        column("description", String),
        column("cost_points", Integer),
        column("is_available", Boolean),
    )

    namespace = uuid.UUID("6f3b1c1e-0000-4000-8000-000000000021")
    rows = [
        {
            "id": uuid.uuid5(namespace, entry["slug"]),
            "is_available": False,
            **entry,
        }
        for entry in _REWARDS
    ]
    op.bulk_insert(rewards, rows)


#: Kept in step with `app/modules/points/catalogue.py`. Duplicated rather than
#: imported, deliberately: a migration that imports application code stops
#: applying the moment that code is refactored, and a migration must be
#: replayable against the schema it was written for.
_REWARDS = [
    {
        "slug": "ad-free-month",
        "title": "A month without the support banner",
        "description": (
            "Hides the funding banner for thirty days. Costs the project nothing, "
            "which is why it is first."
        ),
        "cost_points": 200,
    },
    {
        "slug": "extra-price-searches",
        "title": "Ten extra live price searches",
        "description": (
            "Live comparison runs on a metered free tier with a hard monthly cap "
            "(ADR-008). This spends some of that allowance on you."
        ),
        "cost_points": 500,
    },
    {
        "slug": "priority-receipt-processing",
        "title": "Priority receipt processing",
        "description": (
            "Your next twenty receipts jump the OCR queue. On a single-worker "
            "deployment that is a real, if modest, difference."
        ),
        "cost_points": 750,
    },
    {
        "slug": "contributor-badge",
        "title": "Contributor badge",
        "description": "Shown beside your reports, so other users know who is reliable.",
        "cost_points": 1000,
    },
]


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_receipts_fingerprint_id_receipt_fingerprints"), "receipts", type_="foreignkey"
    )
    op.drop_index(op.f("ix_receipts_fingerprint_id"), table_name="receipts")
    op.drop_column("receipts", "fingerprint_id")
    op.drop_index(op.f("ix_receipt_promotions_user_id"), table_name="receipt_promotions")
    op.drop_index(
        op.f("ix_receipt_promotions_receipt_line_item_id"), table_name="receipt_promotions"
    )
    op.drop_index(op.f("ix_receipt_promotions_receipt_id"), table_name="receipt_promotions")
    op.drop_index(
        op.f("ix_receipt_promotions_price_observation_id"), table_name="receipt_promotions"
    )
    op.drop_table("receipt_promotions")
    op.drop_index(op.f("ix_user_store_pins_user_id"), table_name="user_store_pins")
    op.drop_index(op.f("ix_user_store_pins_store_id"), table_name="user_store_pins")
    op.drop_table("user_store_pins")
    op.drop_index("ix_price_observations_store_id_observed_on", table_name="price_observations")
    op.drop_index(op.f("ix_price_observations_store_id"), table_name="price_observations")
    op.drop_index(
        "ix_price_observations_item_store_date",
        table_name="price_observations",
        postgresql_where=sa.text("retracted_at IS NULL"),
    )
    op.drop_index(op.f("ix_price_observations_canonical_item_id"), table_name="price_observations")
    op.drop_table("price_observations")
    op.drop_index("ix_points_ledger_user_id_created_at", table_name="points_ledger")
    op.drop_index(op.f("ix_points_ledger_user_id"), table_name="points_ledger")
    op.drop_index(op.f("ix_points_ledger_subject_id"), table_name="points_ledger")
    op.drop_index(op.f("ix_points_ledger_reverses_id"), table_name="points_ledger")
    op.drop_table("points_ledger")
    op.drop_index(
        op.f("ix_item_merge_candidates_right_item_id"), table_name="item_merge_candidates"
    )
    op.drop_index(op.f("ix_item_merge_candidates_left_item_id"), table_name="item_merge_candidates")
    op.drop_table("item_merge_candidates")
    op.drop_index(
        op.f("ix_canonical_item_aliases_canonical_item_id"), table_name="canonical_item_aliases"
    )
    op.drop_table("canonical_item_aliases")
    op.drop_index("ix_stores_pincode_normalized_name", table_name="stores")
    op.drop_index(
        "ix_stores_normalized_name_trgm",
        table_name="stores",
        postgresql_using="gin",
        postgresql_ops={"normalized_name": "gin_trgm_ops"},
    )
    op.drop_index("ix_stores_latitude_longitude", table_name="stores")
    op.drop_index(op.f("ix_stores_brand_slug"), table_name="stores")
    op.drop_table("stores")
    op.drop_table("rewards")
    op.drop_index("ix_receipt_fingerprints_phash_observed_on", table_name="receipt_fingerprints")
    op.drop_index("ix_receipt_fingerprints_observed_on_total", table_name="receipt_fingerprints")
    op.drop_table("receipt_fingerprints")
    op.drop_index(
        "ix_canonical_items_normalized_key_trgm",
        table_name="canonical_items",
        postgresql_using="gin",
        postgresql_ops={"normalized_key": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_canonical_items_category_slug"), table_name="canonical_items")
    op.drop_index("ix_canonical_items_brand_pack_size_pack_unit", table_name="canonical_items")
    op.drop_table("canonical_items")
    # ### end Alembic commands ###
