"""Community reports: claims about local shops, and the trust that weighs them.

For shops that print nothing scannable -- which is most small retail -- there is
no receipt to promote, so a user says what they found and others confirm it.

The anti-abuse design lives in this schema rather than in a moderation queue:
`uq_report_verifications_user_id_report_id` and `uq_community_votes_one_per_user`
are what make one-person-one-vote true, and `user_trust` is derived from
contribution history rather than settable. There is no admin role, because
there is nothing for one to do.

Revision ID: 0022
Revises: 0021
Create Date: 2026-08-26 11:18:36.369231
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community_votes",
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('report', 'comment')",
            name=op.f("ck_community_votes_target_is_a_report_or_a_comment"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_community_votes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_community_votes")),
        sa.UniqueConstraint(
            "user_id", "target_type", "target_id", name="uq_community_votes_one_per_user"
        ),
    )
    op.create_index(
        op.f("ix_community_votes_target_id"), "community_votes", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_community_votes_user_id"), "community_votes", ["user_id"], unique=False
    )
    op.create_table(
        "user_trust",
        sa.Column(
            "score", sa.Numeric(precision=4, scale=3), server_default="0.200", nullable=False
        ),
        sa.Column("accepted_promotions", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "agreed_verifications", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("disputed_reports", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "retracted_contributions", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("rubric_version", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_trust_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_trust")),
        sa.UniqueConstraint("user_id", name="uq_user_trust_user_id"),
    )
    op.create_index(op.f("ix_user_trust_user_id"), "user_trust", ["user_id"], unique=False)
    op.create_table(
        "store_reports",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("canonical_item_id", sa.UUID(), nullable=True),
        sa.Column("item_text", sa.String(length=200), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("agree_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("dispute_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("upvote_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("promoted_observation_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind <> 'good_price' OR price IS NOT NULL",
            name=op.f("ck_store_reports_a_good_price_report_needs_a_price"),
        ),
        sa.CheckConstraint(
            "price IS NULL OR price > 0", name=op.f("ck_store_reports_price_positive")
        ),
        sa.ForeignKeyConstraint(
            ["canonical_item_id"],
            ["canonical_items.id"],
            name=op.f("fk_store_reports_canonical_item_id_canonical_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["promoted_observation_id"],
            ["price_observations.id"],
            name=op.f("fk_store_reports_promoted_observation_id_price_observations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_reports_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_store_reports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_reports")),
    )
    op.create_index(
        op.f("ix_store_reports_canonical_item_id"),
        "store_reports",
        ["canonical_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_store_reports_promoted_observation_id"),
        "store_reports",
        ["promoted_observation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_store_reports_store_id"), "store_reports", ["store_id"], unique=False)
    op.create_index(
        "ix_store_reports_store_id_status", "store_reports", ["store_id", "status"], unique=False
    )
    op.create_index(op.f("ix_store_reports_user_id"), "store_reports", ["user_id"], unique=False)
    op.create_index(
        "ix_store_reports_user_id_created_at",
        "store_reports",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "report_comments",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.String(length=1000), nullable=False),
        sa.Column("upvote_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("retracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["store_reports.id"],
            name=op.f("fk_report_comments_report_id_store_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_report_comments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_comments")),
    )
    op.create_index(
        op.f("ix_report_comments_report_id"), "report_comments", ["report_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_comments_user_id"), "report_comments", ["user_id"], unique=False
    )
    op.create_index(
        "ix_report_comments_user_id_created_at",
        "report_comments",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "report_verifications",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("agrees", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["store_reports.id"],
            name=op.f("fk_report_verifications_report_id_store_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_report_verifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_verifications")),
        sa.UniqueConstraint(
            "user_id", "report_id", name="uq_report_verifications_user_id_report_id"
        ),
    )
    op.create_index(
        op.f("ix_report_verifications_report_id"),
        "report_verifications",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_verifications_user_id"), "report_verifications", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_verifications_user_id"), table_name="report_verifications")
    op.drop_index(op.f("ix_report_verifications_report_id"), table_name="report_verifications")
    op.drop_table("report_verifications")
    op.drop_index("ix_report_comments_user_id_created_at", table_name="report_comments")
    op.drop_index(op.f("ix_report_comments_user_id"), table_name="report_comments")
    op.drop_index(op.f("ix_report_comments_report_id"), table_name="report_comments")
    op.drop_table("report_comments")
    op.drop_index("ix_store_reports_user_id_created_at", table_name="store_reports")
    op.drop_index(op.f("ix_store_reports_user_id"), table_name="store_reports")
    op.drop_index("ix_store_reports_store_id_status", table_name="store_reports")
    op.drop_index(op.f("ix_store_reports_store_id"), table_name="store_reports")
    op.drop_index(op.f("ix_store_reports_promoted_observation_id"), table_name="store_reports")
    op.drop_index(op.f("ix_store_reports_canonical_item_id"), table_name="store_reports")
    op.drop_table("store_reports")
    op.drop_index(op.f("ix_user_trust_user_id"), table_name="user_trust")
    op.drop_table("user_trust")
    op.drop_index(op.f("ix_community_votes_user_id"), table_name="community_votes")
    op.drop_index(op.f("ix_community_votes_target_id"), table_name="community_votes")
    op.drop_table("community_votes")
    # ### end Alembic commands ###
