"""Scraper politeness: host budgets, robots.txt cache, and fetched offers (ADR-012).

All three tables are GLOBAL -- no `user_id`. Politeness to a host is owed by the
deployment, never by whoever happened to type the query, and a price found on a
public page is not owned by the person who searched for it.

`scraper_host_budget` is a sibling of `external_quota_usage`, not an extension.
A quota is a count per period; this must also express *spacing* ("at least ten
seconds since the last request to this host") and *cooldown* ("this host
returned 429, stay away until T"), neither of which a period key can hold.

`robots_policies` caches in Postgres against the usual preference, and for a
stronger reason than the offer cache: an evicted *allow* costs one wasted fetch,
but an evicted *deny* means crawling a path we were told not to. That is a
compliance failure, not a performance one.

Nothing here is reachable on a default deployment: `scraper_enabled_hosts` is
empty, and `ALLOWED_HOSTS` ships with no entries.

Revision ID: 0023
Revises: 0022
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0023"
down_revision: str | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "robots_policies",
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetch_failed", sa.Boolean(), nullable=False),
        sa.Column("status_code", sa.SmallInteger(), nullable=True),
        sa.Column("crawl_delay_seconds", sa.SmallInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_robots_policies")),
        sa.UniqueConstraint("host", name=op.f("uq_robots_policies_host")),
    )
    op.create_index(
        "ix_robots_policies_expires_at", "robots_policies", ["expires_at"], unique=False
    )
    op.create_table(
        "scraped_offer_snapshots",
        sa.Column("rules_version", sa.String(length=20), nullable=False),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("query_text", sa.String(length=255), nullable=False),
        sa.Column("offers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scraped_offer_snapshots")),
    )
    op.create_index(
        "ix_scraped_offer_snapshots_expires_at",
        "scraped_offer_snapshots",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "uq_scraped_offer_snapshots_version_query",
        "scraped_offer_snapshots",
        ["rules_version", "query_hash"],
        unique=True,
    )
    op.create_table(
        "scraper_host_budget",
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column(
            "next_allowed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("min_interval_seconds", sa.SmallInteger(), server_default="10", nullable=False),
        sa.Column("day_key", sa.String(length=10), server_default="", nullable=False),
        sa.Column("requests_today", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("daily_cap", sa.Integer(), server_default="200", nullable=False),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "consecutive_parse_failures",
            sa.SmallInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("last_status", sa.SmallInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scraper_host_budget")),
        sa.UniqueConstraint("host", name=op.f("uq_scraper_host_budget_host")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scraper_host_budget")
    op.drop_index("uq_scraped_offer_snapshots_version_query", table_name="scraped_offer_snapshots")
    op.drop_index("ix_scraped_offer_snapshots_expires_at", table_name="scraped_offer_snapshots")
    op.drop_table("scraped_offer_snapshots")
    op.drop_index("ix_robots_policies_expires_at", table_name="robots_policies")
    op.drop_table("robots_policies")
    # ### end Alembic commands ###
