"""Store confirmations: somebody else saying a pinned shop is really there.

`stores.confirmed_at` shipped with the comment "only confirmed stores anchor a
promoted price" and was then written by nothing, so every user-pinned shop wore
the "not yet confirmed" banner permanently and `STORE_PIN_CONFIRMED` points were
unreachable. This is the missing half.

Tenant-scoped and cascading from `users`, with `UNIQUE (user_id, store_id)` --
the same shape as every other vote in this system, for the same reason: a count
is not a control, and a service-level check is bypassed by the next call site.

Confirmation deliberately does not gate promotion. Requiring it would make user
pins useless for prices, and user pins exist precisely because the small shops
that print nothing scannable are the ones no import knows about.

Revision ID: 0024
Revises: 0023
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0024"
down_revision: str | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_confirmations",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_confirmations_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_store_confirmations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_confirmations")),
        sa.UniqueConstraint("user_id", "store_id", name="uq_store_confirmations_user_id_store_id"),
    )
    op.create_index(
        op.f("ix_store_confirmations_store_id"), "store_confirmations", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_store_confirmations_user_id"), "store_confirmations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_store_confirmations_user_id"), table_name="store_confirmations")
    op.drop_index(op.f("ix_store_confirmations_store_id"), table_name="store_confirmations")
    op.drop_table("store_confirmations")
    # ### end Alembic commands ###
