"""Personalization baseline: purchase signals, profiles, archetypes.

The first migration of the *second* tree (ADR-011). It runs against
SIGNALS_DATABASE_URL and shares no history with `alembic/versions/` -- the
version table is `alembic_version_signals`, in a different database.

Nothing here references `users`, and nothing can: Postgres cannot express a
foreign key across databases. Deletion is carried by the erasure sweep in
`app/core/erasure.py`, and
`test_every_signals_table_is_reachable_by_the_erasure_sweep` is what keeps a
table added later from escaping it.

Revision ID: 0001
Revises:
Create Date: 2026-08-25 22:36:53.650434
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_archetypes",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_archetypes")),
        sa.UniqueConstraint("slug", name=op.f("uq_profile_archetypes_slug")),
    )
    op.create_table(
        "purchase_signals",
        sa.Column("source_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("merchant_normalized", sa.String(length=160), nullable=True),
        sa.Column("category_slug", sa.String(length=80), nullable=True),
        sa.Column("amount_percentile", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_signals")),
        sa.UniqueConstraint(
            "subject_id", "source_digest", name="uq_purchase_signals_subject_id_source_digest"
        ),
    )
    op.create_index(
        op.f("ix_purchase_signals_category_slug"),
        "purchase_signals",
        ["category_slug"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_signals_subject_id"), "purchase_signals", ["subject_id"], unique=False
    )
    op.create_index(
        "ix_purchase_signals_subject_id_occurred_on",
        "purchase_signals",
        ["subject_id", sa.literal_column("occurred_on DESC")],
        unique=False,
    )
    op.create_table(
        "signal_profiles",
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("observation_days", sa.Integer(), nullable=False),
        sa.Column("signal_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("big_purchase_threshold", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("median_big_purchase", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("cadence_days", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("category_affinities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("rubric_version", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_profiles")),
        sa.UniqueConstraint("subject_id", name="uq_signal_profiles_subject_id"),
    )
    op.create_index(
        op.f("ix_signal_profiles_subject_id"), "signal_profiles", ["subject_id"], unique=False
    )
    op.create_table(
        "profile_matches",
        sa.Column("archetype_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["archetype_id"],
            ["profile_archetypes.id"],
            name=op.f("fk_profile_matches_archetype_id_profile_archetypes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_matches")),
        sa.UniqueConstraint(
            "subject_id", "archetype_id", name="uq_profile_matches_subject_id_archetype_id"
        ),
    )
    op.create_index(
        op.f("ix_profile_matches_archetype_id"), "profile_matches", ["archetype_id"], unique=False
    )
    op.create_index(
        op.f("ix_profile_matches_subject_id"), "profile_matches", ["subject_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_matches_subject_id"), table_name="profile_matches")
    op.drop_index(op.f("ix_profile_matches_archetype_id"), table_name="profile_matches")
    op.drop_table("profile_matches")
    op.drop_index(op.f("ix_signal_profiles_subject_id"), table_name="signal_profiles")
    op.drop_table("signal_profiles")
    op.drop_index("ix_purchase_signals_subject_id_occurred_on", table_name="purchase_signals")
    op.drop_index(op.f("ix_purchase_signals_subject_id"), table_name="purchase_signals")
    op.drop_index(op.f("ix_purchase_signals_category_slug"), table_name="purchase_signals")
    op.drop_table("purchase_signals")
    op.drop_table("profile_archetypes")
    # ### end Alembic commands ###
